# https://taskfile.dev
version: "3"

vars:
  CODE_DIRS: src/ tests/
  PYTHON: python3
  PYTHON_VERSION: 3.10

{% if cookiecutter.use_poetry %}
includes:
  poetry:
    taskfile: ./taskfiles/poetry.yml
{% endif %}

tasks:
  bash_version:
    desc: Check bash version
    cmds:
      - bash --version

{% if cookiecutter.use_poetry %}
  default:
    cmds:
      - task: poetry:version
    silent: true
{% endif %}